// Auto-generated seed data from Ash's 2026 Production Sheet
// 160 deals, 4 expenses, extracted from Excel

window.SEED_DATA = {
  "deals": [
    {
      "id": "d0001",
      "orderNumber": "VA-24-714",
      "listingAgent": "",
      "sellingAgent": "",
      "client": "",
      "clientAttribution": "Selling Agent",
      "propertyAddress": "209 River Bend Road, Great Falls, VA 22066",
      "disbursementDate": "2025-01-08",
      "transactionType": "Purchase",
      "settlementFee": 0,
      "lendersPolicy": 2697.65,
      "ownersPolicy": 0,
      "fileFee": 1555.88,
      "revenue": 1141.77
    },
    {
      "id": "d0002",
      "orderNumber": "VA-24-708",
      "listingAgent": "",
      "sellingAgent": "",
      "client": "",
      "clientAttribution": "Selling Agent",
      "propertyAddress": "10407 Van Patten Lane, Great Falls, VA 22066",
      "disbursementDate": "2025-01-31",
      "transactionType": "Refinance",
      "settlementFee": 0,
      "lendersPolicy": 2650.0,
      "ownersPolicy": 0,
      "fileFee": 777.94,
      "revenue": 1872.06
    },
    {
      "id": "d0003",
      "orderNumber": "VA-25-738",
      "listingAgent": "Alan De Gracia",
      "sellingAgent": "Kelly Martinez",
      "client": "Alan De Gracia",
      "clientAttribution": "Listing Agent",
      "propertyAddress": "8627 Hilltop Road, Vienna, VA 22180",
      "disbursementDate": "2025-02-07",
      "transactionType": "Purchase",
      "settlementFee": 1490.0,
      "lendersPolicy": 0,
      "ownersPolicy": 4171.0,
      "fileFee": 1555.88,
      "revenue": 4105.12
    },
    {
      "id": "d0004",
      "orderNumber": "VA-24-724",
      "listingAgent": "Robin Leipfert",
      "sellingAgent": "Kelly Martinez",
      "client": "Robin Leipfert",
      "clientAttribution": "Listing Agent",
      "propertyAddress": "18482 Orchid Drive, Leesburg, VA 20176",
      "disbursementDate": "2025-02-10",
      "transactionType": "Purchase",
      "settlementFee": 1715.0,
      "lendersPolicy": 250.0,
      "ownersPolicy": 5150.5,
      "fileFee": 1555.88,
      "revenue": 5559.62
    },
    {
      "id": "d0005",
      "orderNumber": "VA-25-737",
      "listingAgent": "Rosa Farry",
      "sellingAgent": "Alan De Gracia",
      "client": "Rosa Farry",
      "clientAttribution": "Listing Agent",
      "propertyAddress": "3380 Chelsea Drive, Woodbridge, VA 22192",
      "disbursementDate": "2025-02-14",
      "transactionType": "Purchase",
      "settlementFee": 720.0,
      "lendersPolicy": 231.0,
      "ownersPolicy": 2698.0,
      "fileFee": 1555.88,
      "revenue": 2093.12
    },
    {
      "id": "d0006",
      "orderNumber": "MD-25-742",
      "listingAgent": "Lan Yin",
      "sellingAgent": "Yony Kifle",
      "client": "Lan Yin",
      "clientAttribution": "Listing Agent",
      "propertyAddress": "7605 Harrison Lane, Temple Hills, MD 20748-5419",
      "disbursementDate": "2025-02-20",
      "transactionType": "Purchase",
      "settlementFee": 1090.0,
      "lendersPolicy": 200.0,
      "ownersPolicy": 2601.0,
      "fileFee": 1555.88,
      "revenue": 2335.12
    },
    {
      "id": "d0007",
      "orderNumber": "MD-25-749",
      "listingAgent": "Claudia Cornejo",
      "sellingAgent": "Yony Kifle",
      "client": "Claudia Cornejo",
      "clientAttribution": "Listing Agent",
      "propertyAddress": "5103 Iroquois Street, College Park, MD 20740",
      "disbursementDate": "2025-02-28",
      "transactionType": "Purchase",
      "settlementFee": 0,
      "lendersPolicy": 0,
      "ownersPolicy": 0,
      "fileFee": 1555.88,
      "revenue": -1555.88
    },
    {
      "id": "d0008",
      "orderNumber": "VA-25-756",
      "listingAgent": "Melissa Bianco",
      "sellingAgent": "Kelly Martinez",
      "client": "Melissa Bianco",
      "clientAttribution": "Listing Agent",
      "propertyAddress": "13707 Autumn Vale Court, 29E, Chantilly, VA 20151",
      "disbursementDate": "2025-03-04",
      "transactionType": "Purchase",
      "settlementFee": 895.0,
      "lendersPolicy": 0,
      "ownersPolicy": 1625.0,
      "fileFee": 1555.88,
      "revenue": 964.12
    },
    {
      "id": "d0009",
      "orderNumber": "VA-24-702",
      "listingAgent": "",
      "sellingAgent": "",
      "client": "",
      "clientAttribution": "Selling Agent",
      "propertyAddress": "5710 Scoville Street, Falls Church, VA 22041",
      "disbursementDate": "2025-03-11",
      "transactionType": "Refinance",
      "settlementFee": 0,
      "lendersPolicy": 1030.0,
      "ownersPolicy": 0,
      "fileFee": 777.94,
      "revenue": 252.06
    },
    {
      "id": "d0010",
      "orderNumber": "MD-25-734",
      "listingAgent": "Mandy Kaur",
      "sellingAgent": "Muhammad Sohail",
      "client": "Mandy Kaur",
      "clientAttribution": "Listing Agent",
      "propertyAddress": "404 Wompatuck Court, Silver Spring, MD 20905",
      "disbursementDate": "2025-03-07",
      "transactionType": "Purchase",
      "settlementFee": 1490.0,
      "lendersPolicy": 200.0,
      "ownersPolicy": 3760.5,
      "fileFee": 1555.88,
      "revenue": 3894.62
    },
    {
      "id": "d0011",
      "orderNumber": "VA-25-771",
      "listingAgent": "Amy Mehochko",
      "sellingAgent": "Sam Nassar",
      "client": "Amy Mehochko",
      "clientAttribution": "Listing Agent",
      "propertyAddress": "6804 Signature Circle, Alexandria, VA 22310",
      "disbursementDate": "2025-03-17",
      "transactionType": "Purchase",
      "settlementFee": 0,
      "lendersPolicy": 200.0,
      "ownersPolicy": 3229.0,
      "fileFee": 1555.88,
      "revenue": 1873.12
    },
    {
      "id": "d0012",
      "orderNumber": "VA-25-764",
      "listingAgent": "Rebecca Coughlin",
      "sellingAgent": "Deresse Harris",
      "client": "Rebecca Coughlin",
      "clientAttribution": "Listing Agent",
      "propertyAddress": "9530 Damascus Drive, Manassas, VA 20109",
      "disbursementDate": "2025-03-18",
      "transactionType": "Purchase",
      "settlementFee": 895.0,
      "lendersPolicy": 293.2,
      "ownersPolicy": 2539.75,
      "fileFee": 1555.88,
      "revenue": 2172.07
    },
    {
      "id": "d0013",
      "orderNumber": "VA-25-750",
      "listingAgent": "",
      "sellingAgent": "",
      "client": "",
      "clientAttribution": "Selling Agent",
      "propertyAddress": "6740 Tupper Branch Lane, North Chesterfield, VA 23234",
      "disbursementDate": "2025-03-28",
      "transactionType": "Refinance",
      "settlementFee": 925.0,
      "lendersPolicy": 644.28,
      "ownersPolicy": 0,
      "fileFee": 777.94,
      "revenue": 791.34
    },
    {
      "id": "d0014",
      "orderNumber": "VA-25-786",
      "listingAgent": "",
      "sellingAgent": "",
      "client": "",
      "clientAttribution": "Selling Agent",
      "propertyAddress": "6321 Barrister Road, Chesterfield, VA 23832",
      "disbursementDate": "2025-03-28",
      "transactionType": "Refinance",
      "settlementFee": 500.0,
      "lendersPolicy": 468.16,
      "ownersPolicy": 0,
      "fileFee": 777.94,
      "revenue": 190.22
    },
    {
      "id": "d0015",
      "orderNumber": "MD-24-716",
      "listingAgent": "",
      "sellingAgent": "",
      "client": "",
      "clientAttribution": "Selling Agent",
      "propertyAddress": "6012 Central Avenue, Baltimore, MD 21207",
      "disbursementDate": "2025-04-04",
      "transactionType": "Refinance",
      "settlementFee": 0,
      "lendersPolicy": 590.0,
      "ownersPolicy": 0,
      "fileFee": 777.94,
      "revenue": -187.94
    },
    {
      "id": "d0016",
      "orderNumber": "DC-25-781",
      "listingAgent": "Jorge Amaya",
      "sellingAgent": "Dagmawi Alemayehu",
      "client": "Jorge Amaya",
      "clientAttribution": "Listing Agent",
      "propertyAddress": "926 Euclid Street Northwest, Washington, DC 20001",
      "disbursementDate": "2025-04-04",
      "transactionType": "Purchase",
      "settlementFee": 700.0,
      "lendersPolicy": 150.0,
      "ownersPolicy": 5184.0,
      "fileFee": 1555.88,
      "revenue": 4478.12
    },
    {
      "id": "d0017",
      "orderNumber": "MD-25-795",
      "listingAgent": "Hae-Jeong Kim",
      "sellingAgent": "Adane Gebresenbet",
      "client": "Hae-Jeong Kim",
      "clientAttribution": "Listing Agent",
      "propertyAddress": "6521 Evening Company Circle, Columbia, MD 21044",
      "disbursementDate": "2025-04-04",
      "transactionType": "Purchase",
      "settlementFee": 1120.0,
      "lendersPolicy": 275.0,
      "ownersPolicy": 4261.92,
      "fileFee": 1555.88,
      "revenue": 4101.04
    },
    {
      "id": "d0018",
      "orderNumber": "MD-25-789",
      "listingAgent": "Carole Glick",
      "sellingAgent": "Muhammad Sohail",
      "client": "Carole Glick",
      "clientAttribution": "Listing Agent",
      "propertyAddress": "28 Aston Court, Owings Mills, MD 21117",
      "disbursementDate": "2025-04-07",
      "transactionType": "Purchase",
      "settlementFee": 1025.0,
      "lendersPolicy": 275.0,
      "ownersPolicy": 5373.0,
      "fileFee": 1555.88,
      "revenue": 5117.12
    },
    {
      "id": "d0019",
      "orderNumber": "VA-25-793",
      "listingAgent": "Kevin Muir",
      "sellingAgent": "Penjulee Areevog",
      "client": "Kevin Muir",
      "clientAttribution": "Listing Agent",
      "propertyAddress": "8492 Rippled Creek Court, Springfield, VA 22153",
      "disbursementDate": "2025-04-07",
      "transactionType": "Purchase",
      "settlementFee": 1625.0,
      "lendersPolicy": 200.0,
      "ownersPolicy": 3282.0,
      "fileFee": 1555.88,
      "revenue": 3551.12
    },
    {
      "id": "d0020",
      "orderNumber": "VA-25-798",
      "listingAgent": "Rayvon Abad",
      "sellingAgent": "Claire Torres",
      "client": "Rayvon Abad",
      "clientAttribution": "Listing Agent",
      "propertyAddress": "15812 Aerial View Road, Woodbridge, VA 22193",
      "disbursementDate": "2025-04-08",
      "transactionType": "Purchase",
      "settlementFee": 1455.0,
      "lendersPolicy": 200.0,
      "ownersPolicy": 4429.5,
      "fileFee": 1555.88,
      "revenue": 4528.62
    },
    {
      "id": "d0021",
      "orderNumber": "VA-25-780",
      "listingAgent": "Deni Ferrari",
      "sellingAgent": "Rula Mufti",
      "client": "Deni Ferrari",
      "clientAttribution": "Listing Agent",
      "propertyAddress": "6705 Upland Manor Drive, Gainesville, VA 20155",
      "disbursementDate": "2025-04-08",
      "transactionType": "Purchase",
      "settlementFee": 1120.0,
      "lendersPolicy": 200.0,
      "ownersPolicy": 3103.0,
      "fileFee": 1555.88,
      "revenue": 2867.12
    },
    {
      "id": "d0022",
      "orderNumber": "VA-25-746",
      "listingAgent": "Yony Kifle",
      "sellingAgent": "",
      "client": "Yony Kifle",
      "clientAttribution": "Listing Agent",
      "propertyAddress": "13104 Oat Court, Woodbridge, VA 22193",
      "disbursementDate": "2025-04-08",
      "transactionType": "Purchase",
      "settlementFee": 645.0,
      "lendersPolicy": 0,
      "ownersPolicy": 0,
      "fileFee": 1555.88,
      "revenue": -910.88
    },
    {
      "id": "d0023",
      "orderNumber": "VA-25-811",
      "listingAgent": "Michael Ada",
      "sellingAgent": "Sam Nassar",
      "client": "Michael Ada",
      "clientAttribution": "Listing Agent",
      "propertyAddress": "1010 Harrison Circle, Alexandria, VA 22304",
      "disbursementDate": "2025-04-14",
      "transactionType": "Purchase",
      "settlementFee": 1715.0,
      "lendersPolicy": 200.0,
      "ownersPolicy": 3237.0,
      "fileFee": 1555.88,
      "revenue": 3596.12
    },
    {
      "id": "d0024",
      "orderNumber": "VA-25-801",
      "listingAgent": "Sam Nassar",
      "sellingAgent": "Nora Elbedour",
      "client": "Sam Nassar",
      "clientAttribution": "Listing Agent",
      "propertyAddress": "6749 Jenny Leigh Court, Centreville, VA 20121",
      "disbursementDate": "2025-04-15",
      "transactionType": "Purchase",
      "settlementFee": 1515.0,
      "lendersPolicy": 250.0,
      "ownersPolicy": 2670.25,
      "fileFee": 1555.88,
      "revenue": 2879.37
    },
    {
      "id": "d0025",
      "orderNumber": "DC-25-799",
      "listingAgent": "",
      "sellingAgent": "",
      "client": "",
      "clientAttribution": "Selling Agent",
      "propertyAddress": "339 Riggs Park Place Northeast, Washington, DC 20011",
      "disbursementDate": "2025-04-21",
      "transactionType": "Refinance",
      "settlementFee": 0,
      "lendersPolicy": 1576.8,
      "ownersPolicy": 0,
      "fileFee": 777.94,
      "revenue": 798.86
    },
    {
      "id": "d0026",
      "orderNumber": "MD-25-807",
      "listingAgent": "Bob Simon",
      "sellingAgent": "Adane Gebresenbet",
      "client": "Bob Simon",
      "clientAttribution": "Listing Agent",
      "propertyAddress": "1931 Grinnalds Avenue, Baltimore, MD 21230",
      "disbursementDate": "2025-04-16",
      "transactionType": "Purchase",
      "settlementFee": 0,
      "lendersPolicy": 275.0,
      "ownersPolicy": 876.42,
      "fileFee": 1555.88,
      "revenue": -404.46
    },
    {
      "id": "d0027",
      "orderNumber": "MD-25-790",
      "listingAgent": "Tom Harrison",
      "sellingAgent": "Muhammad Sohail",
      "client": "Tom Harrison",
      "clientAttribution": "Listing Agent",
      "propertyAddress": "1913 Woodlawn Drive, Baltimore, MD 21207",
      "disbursementDate": "2025-04-23",
      "transactionType": "Purchase",
      "settlementFee": 895.0,
      "lendersPolicy": 0,
      "ownersPolicy": 3098.5,
      "fileFee": 1555.88,
      "revenue": 2437.62
    },
    {
      "id": "d0028",
      "orderNumber": "MD-25-829",
      "listingAgent": "",
      "sellingAgent": "",
      "client": "",
      "clientAttribution": "Selling Agent",
      "propertyAddress": "1001 Rosemere Avenue, Silver Spring, MD 20904",
      "disbursementDate": "2025-04-29",
      "transactionType": "Refinance",
      "settlementFee": 500.0,
      "lendersPolicy": 999.5,
      "ownersPolicy": 0,
      "fileFee": 777.94,
      "revenue": 721.56
    },
    {
      "id": "d0029",
      "orderNumber": "Pre-25-198",
      "listingAgent": "",
      "sellingAgent": "Kelly Martinez",
      "client": "Kelly Martinez",
      "clientAttribution": "Selling Agent",
      "propertyAddress": "15198 Sky Valley Drive, Haymarket, VA 20169",
      "disbursementDate": "2025-04-25",
      "transactionType": "Purchase",
      "settlementFee": 0,
      "lendersPolicy": 200.0,
      "ownersPolicy": 5215.2,
      "fileFee": 1555.88,
      "revenue": 3859.32
    },
    {
      "id": "d0030",
      "orderNumber": "MD-25-802",
      "listingAgent": "Diego Rodriguez",
      "sellingAgent": "Yony Kifle",
      "client": "Diego Rodriguez",
      "clientAttribution": "Listing Agent",
      "propertyAddress": "9608 Caltor Lane, Fort Washington, MD 20744",
      "disbursementDate": "2025-04-25",
      "transactionType": "Purchase",
      "settlementFee": 1425.0,
      "lendersPolicy": 275.0,
      "ownersPolicy": 2586.3,
      "fileFee": 1555.88,
      "revenue": 2730.42
    },
    {
      "id": "d0031",
      "orderNumber": "VA-25-819",
      "listingAgent": "Sam Nassar",
      "sellingAgent": "Stuart Nesbitt",
      "client": "Sam Nassar",
      "clientAttribution": "Listing Agent",
      "propertyAddress": "7512 Rolling Road, Springfield, VA 22153",
      "disbursementDate": "2025-04-30",
      "transactionType": "Purchase",
      "settlementFee": 1715.0,
      "lendersPolicy": 200.0,
      "ownersPolicy": 3597.0,
      "fileFee": 1555.88,
      "revenue": 3956.12
    },
    {
      "id": "d0032",
      "orderNumber": "MD-25-827",
      "listingAgent": "Janice Valois",
      "sellingAgent": "Claire Torres",
      "client": "Janice Valois",
      "clientAttribution": "Listing Agent",
      "propertyAddress": "4605 Bettswood Drive, Olney, MD 20832",
      "disbursementDate": "2025-05-05",
      "transactionType": "Purchase",
      "settlementFee": 1715.0,
      "lendersPolicy": 275.0,
      "ownersPolicy": 4214.64,
      "fileFee": 1555.88,
      "revenue": 4648.76
    },
    {
      "id": "d0033",
      "orderNumber": "VA-25-826",
      "listingAgent": "",
      "sellingAgent": "Mansoora Dar",
      "client": "Mansoora Dar",
      "clientAttribution": "Selling Agent",
      "propertyAddress": "2144 Silentree Drive, Vienna, VA 22182",
      "disbursementDate": "2025-05-06",
      "transactionType": "Purchase",
      "settlementFee": 620.0,
      "lendersPolicy": 2053.0,
      "ownersPolicy": 0,
      "fileFee": 1555.88,
      "revenue": 1117.12
    },
    {
      "id": "d0034",
      "orderNumber": "VA-25-835",
      "listingAgent": "Earle Whitmore",
      "sellingAgent": "Sam Nassar",
      "client": "Earle Whitmore",
      "clientAttribution": "Listing Agent",
      "propertyAddress": "4824 Kingston Drive, Annandale, VA 22003",
      "disbursementDate": "2025-05-08",
      "transactionType": "Purchase",
      "settlementFee": 1120.0,
      "lendersPolicy": 200.0,
      "ownersPolicy": 4272.0,
      "fileFee": 1555.88,
      "revenue": 4036.12
    },
    {
      "id": "d0035",
      "orderNumber": "VA-25-834",
      "listingAgent": "John McNamara",
      "sellingAgent": "Kweku Ohene-Okae",
      "client": "John McNamara",
      "clientAttribution": "Listing Agent",
      "propertyAddress": "5400 New London Park Drive, Fairfax, VA 22032",
      "disbursementDate": "2025-05-08",
      "transactionType": "Purchase",
      "settlementFee": 1630.0,
      "lendersPolicy": 200.0,
      "ownersPolicy": 3034.5,
      "fileFee": 1555.88,
      "revenue": 3308.62
    },
    {
      "id": "d0036",
      "orderNumber": "MD-25-853",
      "listingAgent": "Elizabeth Williams",
      "sellingAgent": "Assistant DMV Team Assistant",
      "client": "Elizabeth Williams",
      "clientAttribution": "Listing Agent",
      "propertyAddress": "11312 King George Drive, Unit # 4, Wheaton, MD 20902",
      "disbursementDate": "2025-05-09",
      "transactionType": "Purchase",
      "settlementFee": 1715.0,
      "lendersPolicy": 275.0,
      "ownersPolicy": 1761.6,
      "fileFee": 1555.88,
      "revenue": 2195.72
    },
    {
      "id": "d0037",
      "orderNumber": "DC-25-760",
      "listingAgent": "Christopher Dixon",
      "sellingAgent": "Dee Harris",
      "client": "Christopher Dixon",
      "clientAttribution": "Listing Agent",
      "propertyAddress": "19 Gallatin Street Northeast, Washington, DC 20011",
      "disbursementDate": "2025-05-15",
      "transactionType": "Purchase",
      "settlementFee": 595.0,
      "lendersPolicy": 150.0,
      "ownersPolicy": 5076.0,
      "fileFee": 1555.88,
      "revenue": 4265.12
    },
    {
      "id": "d0038",
      "orderNumber": "MD-25-854",
      "listingAgent": "",
      "sellingAgent": "",
      "client": "",
      "clientAttribution": "Selling Agent",
      "propertyAddress": "5505 Hunting Horn Drive, Ellicott City, MD 21043",
      "disbursementDate": "2025-05-21",
      "transactionType": "Refinance",
      "settlementFee": 500.0,
      "lendersPolicy": 1340.25,
      "ownersPolicy": 0,
      "fileFee": 777.94,
      "revenue": 1062.31
    },
    {
      "id": "d0039",
      "orderNumber": "VA-25-791",
      "listingAgent": "Kelly Martinez",
      "sellingAgent": "Aida McCarthy",
      "client": "Kelly Martinez",
      "clientAttribution": "Listing Agent",
      "propertyAddress": "8004 Clifton Street, Manassas, VA 20109",
      "disbursementDate": "2025-05-20",
      "transactionType": "Purchase",
      "settlementFee": 1630.0,
      "lendersPolicy": 200.0,
      "ownersPolicy": 2394.6,
      "fileFee": 1555.88,
      "revenue": 2668.72
    },
    {
      "id": "d0040",
      "orderNumber": "VA-25-867",
      "listingAgent": "Christine Jones",
      "sellingAgent": "Aurora Guiragossian",
      "client": "Christine Jones",
      "clientAttribution": "Listing Agent",
      "propertyAddress": "6810 Derrell Court, Alexandria, VA 22307",
      "disbursementDate": "2025-05-21",
      "transactionType": "Purchase",
      "settlementFee": 1630.0,
      "lendersPolicy": 200.0,
      "ownersPolicy": 3141.45,
      "fileFee": 1555.88,
      "revenue": 3415.57
    },
    {
      "id": "d0041",
      "orderNumber": "VA-25-828",
      "listingAgent": "Nathan Daniel Johnson",
      "sellingAgent": "Kweku Ohene-Okae",
      "client": "Nathan Daniel Johnson",
      "clientAttribution": "Listing Agent",
      "propertyAddress": "4626 Alliance Way, Fredericksburg, VA 22408",
      "disbursementDate": "2025-05-21",
      "transactionType": "Purchase",
      "settlementFee": 140.0,
      "lendersPolicy": 200.0,
      "ownersPolicy": 1953.96,
      "fileFee": 1555.88,
      "revenue": 738.08
    },
    {
      "id": "d0042",
      "orderNumber": "MD-25-821",
      "listingAgent": "",
      "sellingAgent": "",
      "client": "",
      "clientAttribution": "Selling Agent",
      "propertyAddress": "15615 Twin River Circle, Bowie, MD 20716",
      "disbursementDate": "2025-05-27",
      "transactionType": "Refinance",
      "settlementFee": 500.0,
      "lendersPolicy": 1826.22,
      "ownersPolicy": 0,
      "fileFee": 777.94,
      "revenue": 1548.28
    },
    {
      "id": "d0043",
      "orderNumber": "MD-25-849",
      "listingAgent": "Nurit Coombe",
      "sellingAgent": "Claire Torres",
      "client": "Nurit Coombe",
      "clientAttribution": "Listing Agent",
      "propertyAddress": "1612 Noyes Drive, Silver Spring, MD 20910",
      "disbursementDate": "2025-05-23",
      "transactionType": "Purchase",
      "settlementFee": 1625.0,
      "lendersPolicy": 275.0,
      "ownersPolicy": 4434.6,
      "fileFee": 1555.88,
      "revenue": 4778.72
    },
    {
      "id": "d0044",
      "orderNumber": "MD-25-785",
      "listingAgent": "",
      "sellingAgent": "",
      "client": "",
      "clientAttribution": "Selling Agent",
      "propertyAddress": "2 Slate Mills Court, Catonsville, MD 21228",
      "disbursementDate": "2025-05-29",
      "transactionType": "Refinance",
      "settlementFee": 500.0,
      "lendersPolicy": 917.5,
      "ownersPolicy": 0,
      "fileFee": 777.94,
      "revenue": 639.56
    },
    {
      "id": "d0045",
      "orderNumber": "VA-25-828-A",
      "listingAgent": "",
      "sellingAgent": "",
      "client": "",
      "clientAttribution": "Selling Agent",
      "propertyAddress": "4626 Alliance Way, Fredericksburg, VA 22408",
      "disbursementDate": "2025-05-23",
      "transactionType": "Subordinate Order",
      "settlementFee": 0,
      "lendersPolicy": 0,
      "ownersPolicy": 0,
      "fileFee": 0,
      "revenue": 0
    },
    {
      "id": "d0046",
      "orderNumber": "VA-25-855",
      "listingAgent": "Christopher Russell",
      "sellingAgent": "Mansoora Dar",
      "client": "Christopher Russell",
      "clientAttribution": "Listing Agent",
      "propertyAddress": "20661 Newcomb Terrace, Ashburn, VA 20147",
      "disbursementDate": "2025-05-23",
      "transactionType": "Purchase",
      "settlementFee": 745.0,
      "lendersPolicy": 1697.4,
      "ownersPolicy": 0,
      "fileFee": 1555.88,
      "revenue": 886.52
    },
    {
      "id": "d0047",
      "orderNumber": "MD-25-869",
      "listingAgent": "David Zeff",
      "sellingAgent": "Kelly Martinez",
      "client": "David Zeff",
      "clientAttribution": "Listing Agent",
      "propertyAddress": "20636 Highland Hall Drive, Montgomery Village, MD 20886",
      "disbursementDate": "2025-05-27",
      "transactionType": "Purchase",
      "settlementFee": 1715.0,
      "lendersPolicy": 275.0,
      "ownersPolicy": 3245.4,
      "fileFee": 1555.88,
      "revenue": 3679.52
    },
    {
      "id": "d0048",
      "orderNumber": "VA-25-885",
      "listingAgent": "David Schandler",
      "sellingAgent": "Kelly Martinez",
      "client": "David Schandler",
      "clientAttribution": "Listing Agent",
      "propertyAddress": "12925 Centre Park Circle, 409, Herndon, VA 20171",
      "disbursementDate": "2025-05-29",
      "transactionType": "Purchase",
      "settlementFee": 0,
      "lendersPolicy": 200.0,
      "ownersPolicy": 1189.56,
      "fileFee": 1555.88,
      "revenue": -166.32
    },
    {
      "id": "d0049",
      "orderNumber": "VA-25-893",
      "listingAgent": "Russell Brazil",
      "sellingAgent": "Kelly Martinez",
      "client": "Russell Brazil",
      "clientAttribution": "Listing Agent",
      "propertyAddress": "2304 Riverview Terrace, Alexandria, VA 22303",
      "disbursementDate": "2025-05-29",
      "transactionType": "Purchase",
      "settlementFee": 0,
      "lendersPolicy": 200.0,
      "ownersPolicy": 2967.0,
      "fileFee": 1555.88,
      "revenue": 1611.12
    },
    {
      "id": "d0050",
      "orderNumber": "VA-25-805",
      "listingAgent": "Cheongah Gray",
      "sellingAgent": "Mansoora Dar",
      "client": "Cheongah Gray",
      "clientAttribution": "Listing Agent",
      "propertyAddress": "21543 Trowbridge Square, Ashburn, VA 20147",
      "disbursementDate": "2025-05-30",
      "transactionType": "Purchase",
      "settlementFee": 0,
      "lendersPolicy": 200.0,
      "ownersPolicy": 3327.0,
      "fileFee": 1555.88,
      "revenue": 1971.12
    },
    {
      "id": "d0051",
      "orderNumber": "VA-25-886",
      "listingAgent": "",
      "sellingAgent": "Sam Nassar",
      "client": "Sam Nassar",
      "clientAttribution": "Selling Agent",
      "propertyAddress": "8275 Vermont Place, Manassas, VA 20111",
      "disbursementDate": "2025-05-30",
      "transactionType": "Purchase",
      "settlementFee": 1240.0,
      "lendersPolicy": 280.46,
      "ownersPolicy": 1281.5,
      "fileFee": 1555.88,
      "revenue": 1246.08
    },
    {
      "id": "d0052",
      "orderNumber": "VA-25-873",
      "listingAgent": "Donna Chong",
      "sellingAgent": "Kelly Martinez",
      "client": "Donna Chong",
      "clientAttribution": "Listing Agent",
      "propertyAddress": "2924 Hunter Road, Fairfax, VA 22031",
      "disbursementDate": "2025-05-30",
      "transactionType": "Purchase",
      "settlementFee": 1630.0,
      "lendersPolicy": 0,
      "ownersPolicy": 4844.0,
      "fileFee": 1555.88,
      "revenue": 4918.12
    },
    {
      "id": "d0053",
      "orderNumber": "VA-25-806",
      "listingAgent": "",
      "sellingAgent": "",
      "client": "",
      "clientAttribution": "Selling Agent",
      "propertyAddress": "6820 Old Chesterbrook Road, McLean, VA 22101",
      "disbursementDate": "2025-06-06",
      "transactionType": "Refinance",
      "settlementFee": 520.0,
      "lendersPolicy": 2888.9,
      "ownersPolicy": 0,
      "fileFee": 777.94,
      "revenue": 2630.96
    },
    {
      "id": "d0054",
      "orderNumber": "VA-25-877",
      "listingAgent": "Claire Torres",
      "sellingAgent": "Byron Hudtloff",
      "client": "Byron Hudtloff",
      "clientAttribution": "Listing Agent",
      "propertyAddress": "5340 Holmes Run Parkway, 816, Alexandria, VA 22304",
      "disbursementDate": "2025-06-04",
      "transactionType": "Purchase",
      "settlementFee": 795.0,
      "lendersPolicy": 0,
      "ownersPolicy": 0,
      "fileFee": 1555.88,
      "revenue": -760.88
    },
    {
      "id": "d0055",
      "orderNumber": "Pre-25-192",
      "listingAgent": "",
      "sellingAgent": "Qusai Zaher",
      "client": "Qusai Zaher",
      "clientAttribution": "Selling Agent",
      "propertyAddress": "9711 Meadowlark Road, Vienna, VA 22182",
      "disbursementDate": "2025-06-06",
      "transactionType": "Purchase",
      "settlementFee": 0,
      "lendersPolicy": 200.0,
      "ownersPolicy": 8948.4,
      "fileFee": 1555.88,
      "revenue": 7592.52
    },
    {
      "id": "d0056",
      "orderNumber": "MD-25-897",
      "listingAgent": "Marc Dosik",
      "sellingAgent": "Sam Nassar",
      "client": "Marc Dosik",
      "clientAttribution": "Listing Agent",
      "propertyAddress": "3310 North Leisure World Boulevard, Unit 325, Silver Spring, MD 20906",
      "disbursementDate": "2025-06-09",
      "transactionType": "Purchase",
      "settlementFee": 1120.0,
      "lendersPolicy": 275.0,
      "ownersPolicy": 1454.0,
      "fileFee": 1555.88,
      "revenue": 1293.12
    },
    {
      "id": "d0057",
      "orderNumber": "MD-25-870",
      "listingAgent": "John Keller",
      "sellingAgent": "Muhammad Sohail",
      "client": "John Keller",
      "clientAttribution": "Listing Agent",
      "propertyAddress": "3405 Milford Mill Road, Baltimore, MD 21244",
      "disbursementDate": "2025-06-10",
      "transactionType": "Purchase",
      "settlementFee": 1425.0,
      "lendersPolicy": 275.0,
      "ownersPolicy": 2371.44,
      "fileFee": 1555.88,
      "revenue": 2515.56
    },
    {
      "id": "d0058",
      "orderNumber": "MD-25-901",
      "listingAgent": "Tammi Malave-Smalling",
      "sellingAgent": "Claire Torres",
      "client": "Tammi Malave-Smalling",
      "clientAttribution": "Listing Agent",
      "propertyAddress": "4525 Ratcliff Place, Unit 39-K, Waldorf, MD 20602",
      "disbursementDate": "2025-06-16",
      "transactionType": "Purchase",
      "settlementFee": 530.0,
      "lendersPolicy": 294.2,
      "ownersPolicy": 1733.88,
      "fileFee": 1555.88,
      "revenue": 1002.2
    },
    {
      "id": "d0059",
      "orderNumber": "MD-25-861",
      "listingAgent": "",
      "sellingAgent": "",
      "client": "",
      "clientAttribution": "Selling Agent",
      "propertyAddress": "7156 Tranquility Road, Laurel, MD 20723",
      "disbursementDate": "2025-06-24",
      "transactionType": "Refinance",
      "settlementFee": 695.0,
      "lendersPolicy": 3146.0,
      "ownersPolicy": 0,
      "fileFee": 777.94,
      "revenue": 3063.06
    },
    {
      "id": "d0060",
      "orderNumber": "MD-25-909",
      "listingAgent": "Creig E Northrop III",
      "sellingAgent": "Muhammad Sohail",
      "client": "Creig E Northrop III",
      "clientAttribution": "Listing Agent",
      "propertyAddress": "12719 Folly Quarter Road, Ellicott City, MD 21042",
      "disbursementDate": "2025-06-30",
      "transactionType": "Purchase",
      "settlementFee": 1625.0,
      "lendersPolicy": 275.0,
      "ownersPolicy": 4617.0,
      "fileFee": 1555.88,
      "revenue": 4961.12
    },
    {
      "id": "d0061",
      "orderNumber": "VA-25-922",
      "listingAgent": "Michael Gillies",
      "sellingAgent": "Christine Jones",
      "client": "Michael Gillies",
      "clientAttribution": "Listing Agent",
      "propertyAddress": "5911 Otley Drive, Alexandria, VA 22310",
      "disbursementDate": "2025-07-02",
      "transactionType": "Purchase",
      "settlementFee": 1120.0,
      "lendersPolicy": 200.0,
      "ownersPolicy": 3304.5,
      "fileFee": 1555.88,
      "revenue": 3068.62
    },
    {
      "id": "d0062",
      "orderNumber": "VA-25-948",
      "listingAgent": "Lara Taibl",
      "sellingAgent": "Kelly Martinez",
      "client": "Lara Taibl",
      "clientAttribution": "Listing Agent",
      "propertyAddress": "6602 Ladyslipper Lane, Clifton, VA 20124",
      "disbursementDate": "2025-07-03",
      "transactionType": "Purchase",
      "settlementFee": 1630.0,
      "lendersPolicy": 0,
      "ownersPolicy": 6768.96,
      "fileFee": 1555.88,
      "revenue": 6843.08
    },
    {
      "id": "d0063",
      "orderNumber": "MD-25-934",
      "listingAgent": "Penjulee Areevog",
      "sellingAgent": "Kelly Harris",
      "client": "Penjulee Areevog",
      "clientAttribution": "Listing Agent",
      "propertyAddress": "2410 Saint Clair Drive, Temple Hills, MD 20748",
      "disbursementDate": "2025-07-07",
      "transactionType": "Purchase",
      "settlementFee": 530.0,
      "lendersPolicy": 275.0,
      "ownersPolicy": 2011.08,
      "fileFee": 1555.88,
      "revenue": 1260.2
    },
    {
      "id": "d0064",
      "orderNumber": "VA-25-938",
      "listingAgent": "Nathan Daniel Johnson",
      "sellingAgent": "Penjulee Areevog",
      "client": "Nathan Daniel Johnson",
      "clientAttribution": "Listing Agent",
      "propertyAddress": "14309 South Hall Court, Culpeper, VA 22701",
      "disbursementDate": "2025-07-09",
      "transactionType": "Purchase",
      "settlementFee": 1035.0,
      "lendersPolicy": 200.0,
      "ownersPolicy": 3237.0,
      "fileFee": 1555.88,
      "revenue": 2916.12
    },
    {
      "id": "d0065",
      "orderNumber": "VA-25-906",
      "listingAgent": "Farzad Maghsoudi",
      "sellingAgent": "Farzad Maghsoudi",
      "client": "Farzad Maghsoudi",
      "clientAttribution": "Listing Agent",
      "propertyAddress": "13988 Dancing Twig Drive, Gainesville, VA 20155",
      "disbursementDate": "2025-07-10",
      "transactionType": "Purchase",
      "settlementFee": 1630.0,
      "lendersPolicy": 200.0,
      "ownersPolicy": 3507.0,
      "fileFee": 1555.88,
      "revenue": 3781.12
    },
    {
      "id": "d0066",
      "orderNumber": "VA-25-923",
      "listingAgent": "Dave Adams",
      "sellingAgent": "Yony Kifle",
      "client": "Dave Adams",
      "clientAttribution": "Listing Agent",
      "propertyAddress": "6693 Ordsall Street, Alexandria, VA 22315",
      "disbursementDate": "2025-07-11",
      "transactionType": "Purchase",
      "settlementFee": 1715.0,
      "lendersPolicy": 0,
      "ownersPolicy": 4159.5,
      "fileFee": 1555.88,
      "revenue": 4318.62
    },
    {
      "id": "d0067",
      "orderNumber": "VA-25-951",
      "listingAgent": "Nora Elbedour",
      "sellingAgent": "Susie Branco Zinn",
      "client": "Nora Elbedour",
      "clientAttribution": "Listing Agent",
      "propertyAddress": "4850 Eisenhower Avenue, Unit 204, Alexandria, VA 22304",
      "disbursementDate": "2025-07-11",
      "transactionType": "Purchase",
      "settlementFee": 595.0,
      "lendersPolicy": 0,
      "ownersPolicy": 0,
      "fileFee": 1555.88,
      "revenue": -960.88
    },
    {
      "id": "d0068",
      "orderNumber": "MD-25-857",
      "listingAgent": "",
      "sellingAgent": "",
      "client": "",
      "clientAttribution": "Selling Agent",
      "propertyAddress": "6810 Green Hollow Way, Highland, MD 20777",
      "disbursementDate": "2025-07-11",
      "transactionType": "Purchase",
      "settlementFee": 0,
      "lendersPolicy": 275.0,
      "ownersPolicy": 10767.0,
      "fileFee": 1555.88,
      "revenue": 9486.12
    },
    {
      "id": "d0069",
      "orderNumber": "MD-25-830",
      "listingAgent": "",
      "sellingAgent": "",
      "client": "",
      "clientAttribution": "Selling Agent",
      "propertyAddress": "12807 Sholton Street, Upper Marlboro, MD 20774",
      "disbursementDate": "2025-07-16",
      "transactionType": "Refinance",
      "settlementFee": 695.0,
      "lendersPolicy": 891.5,
      "ownersPolicy": 0,
      "fileFee": 777.94,
      "revenue": 808.56
    },
    {
      "id": "d0070",
      "orderNumber": "VA-25-966",
      "listingAgent": "Nora Elbedour",
      "sellingAgent": "",
      "client": "Nora Elbedour",
      "clientAttribution": "Listing Agent",
      "propertyAddress": "11559 Cavalier Landing Court, Fairfax, VA 22030",
      "disbursementDate": "2025-07-14",
      "transactionType": "Purchase",
      "settlementFee": 0,
      "lendersPolicy": 0,
      "ownersPolicy": 0,
      "fileFee": 1555.88,
      "revenue": -1555.88
    },
    {
      "id": "d0071",
      "orderNumber": "VA-25-970",
      "listingAgent": "Alexsis Doud",
      "sellingAgent": "Saja Elhaj",
      "client": "Alexsis Doud",
      "clientAttribution": "Listing Agent",
      "propertyAddress": "1734 Featherstone Road, Woodbridge, VA 22191",
      "disbursementDate": "2025-07-15",
      "transactionType": "Purchase",
      "settlementFee": 1715.0,
      "lendersPolicy": 200.0,
      "ownersPolicy": 2149.8,
      "fileFee": 1555.88,
      "revenue": 2508.92
    },
    {
      "id": "d0072",
      "orderNumber": "VA-25-967",
      "listingAgent": "Jenny Arias",
      "sellingAgent": "Claire Torres",
      "client": "Jenny Arias",
      "clientAttribution": "Listing Agent",
      "propertyAddress": "6329 Miller Drive, Alexandria, VA 22315",
      "disbursementDate": "2025-07-16",
      "transactionType": "Purchase",
      "settlementFee": 1715.0,
      "lendersPolicy": 200.0,
      "ownersPolicy": 3439.5,
      "fileFee": 1555.88,
      "revenue": 3798.62
    },
    {
      "id": "d0073",
      "orderNumber": "VA-25-953",
      "listingAgent": "Kerry Medaris",
      "sellingAgent": "Farzad Maghsoudi",
      "client": "Kerry Medaris",
      "clientAttribution": "Listing Agent",
      "propertyAddress": "8822 Tanglewood Court, Manassas, VA 20110",
      "disbursementDate": "2025-07-18",
      "transactionType": "Purchase",
      "settlementFee": 0,
      "lendersPolicy": 200.0,
      "ownersPolicy": 1635.72,
      "fileFee": 1555.88,
      "revenue": 279.84
    },
    {
      "id": "d0074",
      "orderNumber": "VA-25-973",
      "listingAgent": "Antonio Rivas",
      "sellingAgent": "Farzad Maghsoudi",
      "client": "Antonio Rivas",
      "clientAttribution": "Listing Agent",
      "propertyAddress": "15000 Rumson Place, Manassas, VA 20111",
      "disbursementDate": "2025-07-21",
      "transactionType": "Purchase",
      "settlementFee": 1215.0,
      "lendersPolicy": 0,
      "ownersPolicy": 3380.0,
      "fileFee": 1555.88,
      "revenue": 3039.12
    },
    {
      "id": "d0075",
      "orderNumber": "MD-25-911",
      "listingAgent": "",
      "sellingAgent": "",
      "client": "",
      "clientAttribution": "Selling Agent",
      "propertyAddress": "1126 Brigadoon Trail, Baltimore, MD 21207",
      "disbursementDate": "2025-07-25",
      "transactionType": "Purchase",
      "settlementFee": 1715.0,
      "lendersPolicy": 275.0,
      "ownersPolicy": 1955.64,
      "fileFee": 1555.88,
      "revenue": 2389.76
    },
    {
      "id": "d0076",
      "orderNumber": "VA-25-963",
      "listingAgent": "Daan De Raedt",
      "sellingAgent": "Nora Elbedour",
      "client": "Daan De Raedt",
      "clientAttribution": "Listing Agent",
      "propertyAddress": "8504 Jeffersonian Court, Vienna, VA 22182",
      "disbursementDate": "2025-07-25",
      "transactionType": "Purchase",
      "settlementFee": 0,
      "lendersPolicy": 200.0,
      "ownersPolicy": 4092.0,
      "fileFee": 1555.88,
      "revenue": 2736.12
    },
    {
      "id": "d0077",
      "orderNumber": "VA-25-962",
      "listingAgent": "Daan De Raedt",
      "sellingAgent": "Kelly Martinez",
      "client": "Daan De Raedt",
      "clientAttribution": "Listing Agent",
      "propertyAddress": "2204 Westcourt Lane, #122, Herndon, VA 20170",
      "disbursementDate": "2025-07-28",
      "transactionType": "Purchase",
      "settlementFee": 1715.0,
      "lendersPolicy": 200.0,
      "ownersPolicy": 1317.48,
      "fileFee": 1555.88,
      "revenue": 1676.6
    },
    {
      "id": "d0078",
      "orderNumber": "MD-25-881",
      "listingAgent": "",
      "sellingAgent": "",
      "client": "",
      "clientAttribution": "Selling Agent",
      "propertyAddress": "503 Cranston Avenue, Upper Marlboro, MD 20774",
      "disbursementDate": "2025-08-01",
      "transactionType": "Refinance",
      "settlementFee": 0,
      "lendersPolicy": 985.5,
      "ownersPolicy": 0,
      "fileFee": 777.94,
      "revenue": 207.56
    },
    {
      "id": "d0079",
      "orderNumber": "VA-25-972",
      "listingAgent": "Steve Angeline",
      "sellingAgent": "Kelly Martinez",
      "client": "Steve Angeline",
      "clientAttribution": "Listing Agent",
      "propertyAddress": "9708 South Park Circle, Fairfax Station, VA 22039",
      "disbursementDate": "2025-07-30",
      "transactionType": "Purchase",
      "settlementFee": 1715.0,
      "lendersPolicy": 254.9,
      "ownersPolicy": 4677.0,
      "fileFee": 1555.88,
      "revenue": 5091.02
    },
    {
      "id": "d0080",
      "orderNumber": "VA-25-981",
      "listingAgent": "Melissa Denise Kaijuka",
      "sellingAgent": "Nassar Group",
      "client": "Melissa Denise Kaijuka",
      "clientAttribution": "Listing Agent",
      "propertyAddress": "9711 Handerson Place, Unit 206, Manassas Park, VA 20111",
      "disbursementDate": "2025-07-31",
      "transactionType": "Purchase",
      "settlementFee": 1120.0,
      "lendersPolicy": 0,
      "ownersPolicy": 1363.1,
      "fileFee": 1555.88,
      "revenue": 927.22
    },
    {
      "id": "d0081",
      "orderNumber": "Pre-25-229",
      "listingAgent": "",
      "sellingAgent": "",
      "client": "",
      "clientAttribution": "Selling Agent",
      "propertyAddress": "6608 Schurtz Street, Alexandria, VA 22310",
      "disbursementDate": "2025-07-31",
      "transactionType": "Purchase",
      "settlementFee": 0,
      "lendersPolicy": 0,
      "ownersPolicy": 0,
      "fileFee": 1555.88,
      "revenue": -1555.88
    },
    {
      "id": "d0082",
      "orderNumber": "MD-25-965",
      "listingAgent": "Laura M. Snyder",
      "sellingAgent": "Muhammad Sohail",
      "client": "Laura M. Snyder",
      "clientAttribution": "Listing Agent",
      "propertyAddress": "1012 Glenangus Drive, Bel Air, MD 21015",
      "disbursementDate": "2025-07-31",
      "transactionType": "Purchase",
      "settlementFee": 1715.0,
      "lendersPolicy": 275.0,
      "ownersPolicy": 4994.76,
      "fileFee": 1555.88,
      "revenue": 5428.88
    },
    {
      "id": "d0083",
      "orderNumber": "VA-25-925",
      "listingAgent": "",
      "sellingAgent": "",
      "client": "",
      "clientAttribution": "Selling Agent",
      "propertyAddress": "41190 Abbey Knoll Court, Brambleton, VA 20148",
      "disbursementDate": "2025-08-08",
      "transactionType": "Refinance",
      "settlementFee": 695.0,
      "lendersPolicy": 1453.1,
      "ownersPolicy": 0,
      "fileFee": 777.94,
      "revenue": 1370.16
    },
    {
      "id": "d0084",
      "orderNumber": "FL-25-993",
      "listingAgent": "",
      "sellingAgent": "",
      "client": "",
      "clientAttribution": "Selling Agent",
      "propertyAddress": "633 Coral Way, Fort Lauderdale, FL 33301",
      "disbursementDate": "2025-08-05",
      "transactionType": "Refinance",
      "settlementFee": 0,
      "lendersPolicy": 16115.62,
      "ownersPolicy": 0,
      "fileFee": 777.94,
      "revenue": 15337.68
    },
    {
      "id": "d0085",
      "orderNumber": "MD-25-980",
      "listingAgent": "Tony Trung Le",
      "sellingAgent": "Muhammad Sohail",
      "client": "Tony Trung Le",
      "clientAttribution": "Listing Agent",
      "propertyAddress": "5941 Elk Forest Court, Elkridge, MD 21075",
      "disbursementDate": "2025-08-08",
      "transactionType": "Purchase",
      "settlementFee": 0,
      "lendersPolicy": 275.0,
      "ownersPolicy": 3198.12,
      "fileFee": 1555.88,
      "revenue": 1917.24
    },
    {
      "id": "d0086",
      "orderNumber": "VA-25-978",
      "listingAgent": "Verria Hairston",
      "sellingAgent": "Kelly Martinez",
      "client": "Verria Hairston",
      "clientAttribution": "Listing Agent",
      "propertyAddress": "14828 Anderson Court, Woodbridge, VA 22193",
      "disbursementDate": "2025-08-08",
      "transactionType": "Purchase",
      "settlementFee": 225.0,
      "lendersPolicy": 200.0,
      "ownersPolicy": 2012.71,
      "fileFee": 1555.88,
      "revenue": 881.83
    },
    {
      "id": "d0087",
      "orderNumber": "MD-25-996",
      "listingAgent": "Lloidy Guevara",
      "sellingAgent": "Adane Gebresenbet",
      "client": "Lloidy Guevara",
      "clientAttribution": "Listing Agent",
      "propertyAddress": "8031 New Riggs Road, Hyattsville, MD 20783",
      "disbursementDate": "2025-08-12",
      "transactionType": "Purchase",
      "settlementFee": 1476.0,
      "lendersPolicy": 275.0,
      "ownersPolicy": 2460.14,
      "fileFee": 1555.88,
      "revenue": 2655.26
    },
    {
      "id": "d0088",
      "orderNumber": "VA-25-986",
      "listingAgent": "Monica Leszczak",
      "sellingAgent": "Yony Kifle",
      "client": "Monica Leszczak",
      "clientAttribution": "Listing Agent",
      "propertyAddress": "5904 Mayflower Court, Alexandria, VA 22312",
      "disbursementDate": "2025-08-12",
      "transactionType": "Purchase",
      "settlementFee": 1120.0,
      "lendersPolicy": 200.0,
      "ownersPolicy": 1537.8,
      "fileFee": 1555.88,
      "revenue": 1301.92
    },
    {
      "id": "d0089",
      "orderNumber": "MD-25-825",
      "listingAgent": "",
      "sellingAgent": "",
      "client": "",
      "clientAttribution": "Selling Agent",
      "propertyAddress": "422 North Lakewood Avenue, Baltimore, MD 21224",
      "disbursementDate": "2025-08-13",
      "transactionType": "Refinance",
      "settlementFee": 695.0,
      "lendersPolicy": 445.05,
      "ownersPolicy": 0,
      "fileFee": 777.94,
      "revenue": 362.11
    },
    {
      "id": "d0090",
      "orderNumber": "VA-25-1008",
      "listingAgent": "Sanjeev Gupta",
      "sellingAgent": "Naimeh Elliftawi",
      "client": "Sanjeev Gupta",
      "clientAttribution": "Listing Agent",
      "propertyAddress": "14018B Grumble Jones Court, Centreville, VA 20121",
      "disbursementDate": "2025-08-13",
      "transactionType": "Purchase",
      "settlementFee": 1715.0,
      "lendersPolicy": 200.0,
      "ownersPolicy": 2296.68,
      "fileFee": 1555.88,
      "revenue": 2655.8
    },
    {
      "id": "d0091",
      "orderNumber": "VA-25-998",
      "listingAgent": "Paula Heard",
      "sellingAgent": "Christine Jones",
      "client": "Paula Heard",
      "clientAttribution": "Listing Agent",
      "propertyAddress": "12367 Wadsworth Way, Woodbridge, VA 22192",
      "disbursementDate": "2025-08-14",
      "transactionType": "Purchase",
      "settlementFee": 1715.0,
      "lendersPolicy": 200.0,
      "ownersPolicy": 1586.76,
      "fileFee": 1555.88,
      "revenue": 1945.88
    },
    {
      "id": "d0092",
      "orderNumber": "VA-25-994",
      "listingAgent": "William Gaskins",
      "sellingAgent": "Christine Jones",
      "client": "William Gaskins",
      "clientAttribution": "Listing Agent",
      "propertyAddress": "3465 South Wakefield Street, Arlington, VA 22206",
      "disbursementDate": "2025-08-14",
      "transactionType": "Purchase",
      "settlementFee": 1120.0,
      "lendersPolicy": 200.0,
      "ownersPolicy": 3079.5,
      "fileFee": 1555.88,
      "revenue": 2843.62
    },
    {
      "id": "d0093",
      "orderNumber": "MD-25-989",
      "listingAgent": "Frank Evans, Jr.",
      "sellingAgent": "Yony Kifle",
      "client": "Frank Evans, Jr.",
      "clientAttribution": "Listing Agent",
      "propertyAddress": "13209 Chalfont Avenue, Fort Washington, MD 20744",
      "disbursementDate": "2025-08-15",
      "transactionType": "Purchase",
      "settlementFee": 0,
      "lendersPolicy": 275.0,
      "ownersPolicy": 2870.4,
      "fileFee": 1555.88,
      "revenue": 1589.52
    },
    {
      "id": "d0094",
      "orderNumber": "MD-25-984",
      "listingAgent": "Ted Spenadel",
      "sellingAgent": "Claire Torres",
      "client": "Ted Spenadel",
      "clientAttribution": "Listing Agent",
      "propertyAddress": "20315 Beaconfield Terrace, # 202, Germantown, MD 20874",
      "disbursementDate": "2025-08-20",
      "transactionType": "Purchase",
      "settlementFee": 1715.0,
      "lendersPolicy": 275.0,
      "ownersPolicy": 1733.88,
      "fileFee": 1555.88,
      "revenue": 2168.0
    },
    {
      "id": "d0095",
      "orderNumber": "VA-25-1016",
      "listingAgent": "Brittany L Sims",
      "sellingAgent": "Claire Torres",
      "client": "Brittany L Sims",
      "clientAttribution": "Listing Agent",
      "propertyAddress": "16647 Space More Circle, Woodbridge, VA 22191",
      "disbursementDate": "2025-08-22",
      "transactionType": "Purchase",
      "settlementFee": 1120.0,
      "lendersPolicy": 200.0,
      "ownersPolicy": 4093.0,
      "fileFee": 1555.88,
      "revenue": 3857.12
    },
    {
      "id": "d0096",
      "orderNumber": "DC-25-1028",
      "listingAgent": "Kim Jones",
      "sellingAgent": "Yony Kifle",
      "client": "Kim Jones",
      "clientAttribution": "Listing Agent",
      "propertyAddress": "3914 20th Street Northeast, Washington, DC 20018",
      "disbursementDate": "2025-08-22",
      "transactionType": "Purchase",
      "settlementFee": 1490.0,
      "lendersPolicy": 150.0,
      "ownersPolicy": 5853.6,
      "fileFee": 1555.88,
      "revenue": 5937.72
    },
    {
      "id": "d0097",
      "orderNumber": "VA-25-1027",
      "listingAgent": "Laura Lawlor",
      "sellingAgent": "Nassar Group",
      "client": "Laura Lawlor",
      "clientAttribution": "Listing Agent",
      "propertyAddress": "20656 Meadowthrash Court, Ashburn, VA 20147",
      "disbursementDate": "2025-08-25",
      "transactionType": "Purchase",
      "settlementFee": 1120.0,
      "lendersPolicy": 200.0,
      "ownersPolicy": 4318.0,
      "fileFee": 1555.88,
      "revenue": 4082.12
    },
    {
      "id": "d0098",
      "orderNumber": "DC-25-1000",
      "listingAgent": "",
      "sellingAgent": "",
      "client": "",
      "clientAttribution": "Selling Agent",
      "propertyAddress": "3030 K Street Northwest, Unit 305, Washington, DC 20007",
      "disbursementDate": "2025-08-25",
      "transactionType": "Refinance",
      "settlementFee": 695.0,
      "lendersPolicy": 3660.0,
      "ownersPolicy": 0,
      "fileFee": 777.94,
      "revenue": 3577.06
    },
    {
      "id": "d0099",
      "orderNumber": "VA-25-1024",
      "listingAgent": "Michael Crosby",
      "sellingAgent": "Rula Mufti",
      "client": "Michael Crosby",
      "clientAttribution": "Listing Agent",
      "propertyAddress": "7413 Whisperwood Drive, Warrenton, VA 20187",
      "disbursementDate": "2025-08-26",
      "transactionType": "Purchase",
      "settlementFee": 1715.0,
      "lendersPolicy": 243.18,
      "ownersPolicy": 3642.0,
      "fileFee": 1555.88,
      "revenue": 4044.3
    },
    {
      "id": "d0100",
      "orderNumber": "MD-25-856",
      "listingAgent": "",
      "sellingAgent": "",
      "client": "",
      "clientAttribution": "Selling Agent",
      "propertyAddress": "15625 Twin River Circle, Bowie, MD 20716",
      "disbursementDate": "2025-09-04",
      "transactionType": "Refinance",
      "settlementFee": 0,
      "lendersPolicy": 3018.0,
      "ownersPolicy": 0,
      "fileFee": 777.94,
      "revenue": 2240.06
    },
    {
      "id": "d0101",
      "orderNumber": "FL-25-1007",
      "listingAgent": "",
      "sellingAgent": "",
      "client": "",
      "clientAttribution": "Selling Agent",
      "propertyAddress": "1103 Arthur Avenue, Lehigh Acres, FL 33936",
      "disbursementDate": "2025-09-04",
      "transactionType": "Refinance",
      "settlementFee": 0,
      "lendersPolicy": 1092.5,
      "ownersPolicy": 0,
      "fileFee": 777.94,
      "revenue": 314.56
    },
    {
      "id": "d0102",
      "orderNumber": "VA-25-1017",
      "listingAgent": "Nassar Group",
      "sellingAgent": "Maynor R. Herrera",
      "client": "Nassar Group",
      "clientAttribution": "Listing Agent",
      "propertyAddress": "9204 Arrington Farm Court, Manassas, VA 20111",
      "disbursementDate": "2025-08-29",
      "transactionType": "Purchase",
      "settlementFee": 595.0,
      "lendersPolicy": 0,
      "ownersPolicy": 0,
      "fileFee": 1555.88,
      "revenue": -960.88
    },
    {
      "id": "d0103",
      "orderNumber": "VA-25-1042",
      "listingAgent": "",
      "sellingAgent": "",
      "client": "",
      "clientAttribution": "Selling Agent",
      "propertyAddress": "7725 Markham Grant Lane, Alexandria, VA 22315",
      "disbursementDate": "2025-09-08",
      "transactionType": "Refinance",
      "settlementFee": 695.0,
      "lendersPolicy": 1128.0,
      "ownersPolicy": 0,
      "fileFee": 777.94,
      "revenue": 1045.06
    },
    {
      "id": "d0104",
      "orderNumber": "VA-25-1029",
      "listingAgent": "Dimitri Sotiropoulos",
      "sellingAgent": "Kiros Asmamaw",
      "client": "Dimitri Sotiropoulos",
      "clientAttribution": "Listing Agent",
      "propertyAddress": "3800 Powell Lane, Unit 1002, Falls Church, VA 22041",
      "disbursementDate": "2025-09-02",
      "transactionType": "Purchase",
      "settlementFee": 1540.0,
      "lendersPolicy": 200.0,
      "ownersPolicy": 2120.42,
      "fileFee": 1555.88,
      "revenue": 2304.54
    },
    {
      "id": "d0105",
      "orderNumber": "VA-25-1026",
      "listingAgent": "Kelly Martinez",
      "sellingAgent": "Karen Briscoe",
      "client": "Kelly Martinez",
      "clientAttribution": "Listing Agent",
      "propertyAddress": "7774 Quail Run Lane, Manassas, VA 20109",
      "disbursementDate": "2025-09-03",
      "transactionType": "Purchase",
      "settlementFee": 1715.0,
      "lendersPolicy": 200.0,
      "ownersPolicy": 1890.31,
      "fileFee": 1555.88,
      "revenue": 2249.43
    },
    {
      "id": "d0106",
      "orderNumber": "DC-25-1055",
      "listingAgent": "Raneem Nassar",
      "sellingAgent": "",
      "client": "Raneem Nassar",
      "clientAttribution": "Listing Agent",
      "propertyAddress": "4414 Dubois Place Southeast, Washington, DC 20019",
      "disbursementDate": "2025-09-03",
      "transactionType": "Purchase",
      "settlementFee": 0,
      "lendersPolicy": 0,
      "ownersPolicy": 0,
      "fileFee": 1555.88,
      "revenue": -1555.88
    },
    {
      "id": "d0107",
      "orderNumber": "MD-25-969",
      "listingAgent": "Deric Beckett",
      "sellingAgent": "Yony Kifle",
      "client": "Deric Beckett",
      "clientAttribution": "Listing Agent",
      "propertyAddress": "1621 Ramsay Street, Baltimore, MD 21223",
      "disbursementDate": "2025-09-03",
      "transactionType": "Purchase",
      "settlementFee": 1120.0,
      "lendersPolicy": 0,
      "ownersPolicy": 360.0,
      "fileFee": 1555.88,
      "revenue": -75.88
    },
    {
      "id": "d0108",
      "orderNumber": "VA-25-1036",
      "listingAgent": "John C. Ashton",
      "sellingAgent": "Nassar Group",
      "client": "John C. Ashton",
      "clientAttribution": "Listing Agent",
      "propertyAddress": "5503 Chestermill Court, Fairfax, VA 22030",
      "disbursementDate": "2025-09-08",
      "transactionType": "Purchase",
      "settlementFee": 1515.0,
      "lendersPolicy": 200.0,
      "ownersPolicy": 5270.0,
      "fileFee": 1555.88,
      "revenue": 5429.12
    },
    {
      "id": "d0109",
      "orderNumber": "VA-25-995",
      "listingAgent": "Sasha Jaggar",
      "sellingAgent": "Raneem Nassar",
      "client": "Sasha Jaggar",
      "clientAttribution": "Listing Agent",
      "propertyAddress": "126 North Baylor Drive, Unit 142, Sterling, VA 20164",
      "disbursementDate": "2025-09-11",
      "transactionType": "Purchase",
      "settlementFee": 1120.0,
      "lendersPolicy": 250.0,
      "ownersPolicy": 1358.8,
      "fileFee": 1555.88,
      "revenue": 1172.92
    },
    {
      "id": "d0110",
      "orderNumber": "VA-25-1015",
      "listingAgent": "Nassar Group",
      "sellingAgent": "Rey Gomez",
      "client": "Nassar Group",
      "clientAttribution": "Listing Agent",
      "propertyAddress": "14611 Featherstone Gate Drive, Woodbridge, VA 22191",
      "disbursementDate": "2025-09-16",
      "transactionType": "Purchase",
      "settlementFee": 1630.0,
      "lendersPolicy": 200.0,
      "ownersPolicy": 2154.7,
      "fileFee": 1555.88,
      "revenue": 2428.82
    },
    {
      "id": "d0111",
      "orderNumber": "MD-25-1037",
      "listingAgent": "",
      "sellingAgent": "",
      "client": "",
      "clientAttribution": "Selling Agent",
      "propertyAddress": "6919 Real Princess Lane, Baltimore, MD 21207",
      "disbursementDate": "2025-09-29",
      "transactionType": "Refinance",
      "settlementFee": 0,
      "lendersPolicy": 957.5,
      "ownersPolicy": 0,
      "fileFee": 777.94,
      "revenue": 179.56
    },
    {
      "id": "d0112",
      "orderNumber": "MD-25-1039",
      "listingAgent": "Debbie Gottwais",
      "sellingAgent": "Muhammad Sohail",
      "client": "Debbie Gottwais",
      "clientAttribution": "Listing Agent",
      "propertyAddress": "9194 Old Frederick Road, Ellicott City, MD 21042",
      "disbursementDate": "2025-09-25",
      "transactionType": "Purchase",
      "settlementFee": 1625.0,
      "lendersPolicy": 275.0,
      "ownersPolicy": 4025.52,
      "fileFee": 1555.88,
      "revenue": 4369.64
    },
    {
      "id": "d0113",
      "orderNumber": "MD-25-884",
      "listingAgent": "",
      "sellingAgent": "",
      "client": "",
      "clientAttribution": "Selling Agent",
      "propertyAddress": "6005 Manor Oak Way, Bethesda, MD 20814",
      "disbursementDate": "2025-09-30",
      "transactionType": "Refinance",
      "settlementFee": 695.0,
      "lendersPolicy": 3620.0,
      "ownersPolicy": 0,
      "fileFee": 777.94,
      "revenue": 3537.06
    },
    {
      "id": "d0114",
      "orderNumber": "DC-25-1074",
      "listingAgent": "",
      "sellingAgent": "",
      "client": "",
      "clientAttribution": "Selling Agent",
      "propertyAddress": "4213 Fort Dupont Street Southeast, Washington, DC 20020",
      "disbursementDate": "2025-09-25",
      "transactionType": "Purchase",
      "settlementFee": 0,
      "lendersPolicy": 150.0,
      "ownersPolicy": 2322.0,
      "fileFee": 1555.88,
      "revenue": 916.12
    },
    {
      "id": "d0115",
      "orderNumber": "VA-25-1020",
      "listingAgent": "Nassar Group",
      "sellingAgent": "Lauren Reeves",
      "client": "Nassar Group",
      "clientAttribution": "Listing Agent",
      "propertyAddress": "14613 Featherstone Gate Drive, Woodbridge, VA 22191",
      "disbursementDate": "2025-09-26",
      "transactionType": "Purchase",
      "settlementFee": 1715.0,
      "lendersPolicy": 244.7,
      "ownersPolicy": 2154.7,
      "fileFee": 1555.88,
      "revenue": 2558.52
    },
    {
      "id": "d0116",
      "orderNumber": "VA-25-1072",
      "listingAgent": "Manar Aman",
      "sellingAgent": "Yony Kifle",
      "client": "Manar Aman",
      "clientAttribution": "Listing Agent",
      "propertyAddress": "5505 Seminary Road, 905N, Falls Church, VA 22041",
      "disbursementDate": "2025-09-26",
      "transactionType": "Purchase",
      "settlementFee": 0,
      "lendersPolicy": 200.0,
      "ownersPolicy": 2321.16,
      "fileFee": 1555.88,
      "revenue": 965.28
    },
    {
      "id": "d0117",
      "orderNumber": "Pre-25-261",
      "listingAgent": "",
      "sellingAgent": "",
      "client": "",
      "clientAttribution": "Selling Agent",
      "propertyAddress": "714 1st Court, Palm Harbor, FL 34684",
      "disbursementDate": "2025-09-30",
      "transactionType": "Purchase",
      "settlementFee": 0,
      "lendersPolicy": 25.0,
      "ownersPolicy": 1460.0,
      "fileFee": 1555.88,
      "revenue": -70.88
    },
    {
      "id": "d0118",
      "orderNumber": "VA-25-1081",
      "listingAgent": "Chuck LaRock",
      "sellingAgent": "Sam Nassar",
      "client": "Chuck LaRock",
      "clientAttribution": "Listing Agent",
      "propertyAddress": "20162 Hardwood Terrace, Ashburn, VA 20147",
      "disbursementDate": "2025-09-30",
      "transactionType": "Purchase",
      "settlementFee": 1120.0,
      "lendersPolicy": 200.0,
      "ownersPolicy": 2967.0,
      "fileFee": 1555.88,
      "revenue": 2731.12
    },
    {
      "id": "d0119",
      "orderNumber": "MD-25-1073",
      "listingAgent": "Fred Gomez",
      "sellingAgent": "Claire Torres",
      "client": "Fred Gomez",
      "clientAttribution": "Listing Agent",
      "propertyAddress": "1733 Rhodesia Avenue, Fort Washington, MD 20744",
      "disbursementDate": "2025-10-06",
      "transactionType": "Purchase",
      "settlementFee": 1625.0,
      "lendersPolicy": 275.0,
      "ownersPolicy": 2898.12,
      "fileFee": 1555.88,
      "revenue": 3242.24
    },
    {
      "id": "d0120",
      "orderNumber": "MD-25-1076",
      "listingAgent": "Paul M. Buckmaster",
      "sellingAgent": "Muhammad Sohail",
      "client": "Paul M. Buckmaster",
      "clientAttribution": "Listing Agent",
      "propertyAddress": "7311 Falling Leaves Court, Marriottsville, MD 21104",
      "disbursementDate": "2025-10-06",
      "transactionType": "Purchase",
      "settlementFee": 135.0,
      "lendersPolicy": 275.0,
      "ownersPolicy": 4616.52,
      "fileFee": 1555.88,
      "revenue": 3470.64
    },
    {
      "id": "d0121",
      "orderNumber": "VA-25-1096",
      "listingAgent": "Andreia Williams",
      "sellingAgent": "Yaztka Allen",
      "client": "Andreia Williams",
      "clientAttribution": "Listing Agent",
      "propertyAddress": "2661 McGuffeys Court, Woodbridge, VA 22191",
      "disbursementDate": "2025-10-08",
      "transactionType": "Purchase",
      "settlementFee": 0,
      "lendersPolicy": 200.0,
      "ownersPolicy": 2273.0,
      "fileFee": 1555.88,
      "revenue": 917.12
    },
    {
      "id": "d0122",
      "orderNumber": "VA-25-1085",
      "listingAgent": "Elena Gorbounova",
      "sellingAgent": "Claire Torres",
      "client": "Elena Gorbounova",
      "clientAttribution": "Listing Agent",
      "propertyAddress": "5505 Seminary Rd, 505n, Falls Church, VA 22041",
      "disbursementDate": "2025-10-10",
      "transactionType": "Purchase",
      "settlementFee": 1035.0,
      "lendersPolicy": 200.0,
      "ownersPolicy": 2213.45,
      "fileFee": 1555.88,
      "revenue": 1892.57
    },
    {
      "id": "d0123",
      "orderNumber": "MD-25-1094",
      "listingAgent": "Corey Lancaster",
      "sellingAgent": "Adane Gebresenbet",
      "client": "Corey Lancaster",
      "clientAttribution": "Listing Agent",
      "propertyAddress": "14602 Mc Knew Road, Burtonsville, MD 20866",
      "disbursementDate": "2025-10-15",
      "transactionType": "Purchase",
      "settlementFee": 1490.0,
      "lendersPolicy": 275.0,
      "ownersPolicy": 2343.72,
      "fileFee": 1555.88,
      "revenue": 2552.84
    },
    {
      "id": "d0124",
      "orderNumber": "MD-25-1107",
      "listingAgent": "Nassar Group",
      "sellingAgent": "",
      "client": "Nassar Group",
      "clientAttribution": "Listing Agent",
      "propertyAddress": "8830 Piney Branch Rd, Unit 510, Silver Spring, MD 20903",
      "disbursementDate": "2025-10-17",
      "transactionType": "Purchase",
      "settlementFee": 595.0,
      "lendersPolicy": 0,
      "ownersPolicy": 0,
      "fileFee": 1555.88,
      "revenue": -960.88
    },
    {
      "id": "d0125",
      "orderNumber": "MD-25-1099",
      "listingAgent": "Eva Harris",
      "sellingAgent": "Penjulee Areevong",
      "client": "Eva Harris",
      "clientAttribution": "Listing Agent",
      "propertyAddress": "1802 Village Green Drive, D-97, Landover, MD 20785",
      "disbursementDate": "2025-10-20",
      "transactionType": "Purchase",
      "settlementFee": 135.0,
      "lendersPolicy": 294.2,
      "ownersPolicy": 1623.0,
      "fileFee": 1555.88,
      "revenue": 496.32
    },
    {
      "id": "d0126",
      "orderNumber": "VA-25-1108",
      "listingAgent": "Mary Ashley Zimmermann",
      "sellingAgent": "William Eging",
      "client": "Mary Ashley Zimmermann",
      "clientAttribution": "Listing Agent",
      "propertyAddress": "726 South Patrick Street, Alexandria, VA 22314",
      "disbursementDate": "2025-10-20",
      "transactionType": "Purchase",
      "settlementFee": 1715.0,
      "lendersPolicy": 200.0,
      "ownersPolicy": 5319.78,
      "fileFee": 1555.88,
      "revenue": 5678.9
    },
    {
      "id": "d0127",
      "orderNumber": "VA-25-1109-A",
      "listingAgent": "",
      "sellingAgent": "",
      "client": "",
      "clientAttribution": "Selling Agent",
      "propertyAddress": "29 Pepper Tree Court, Warrenton, VA 20186",
      "disbursementDate": "2025-10-22",
      "transactionType": "Subordinate Order",
      "settlementFee": 0,
      "lendersPolicy": 0,
      "ownersPolicy": 0,
      "fileFee": 0,
      "revenue": 0
    },
    {
      "id": "d0128",
      "orderNumber": "VA-25-1109",
      "listingAgent": "Wendy Johnson",
      "sellingAgent": "Yaztka Allen",
      "client": "Wendy Johnson",
      "clientAttribution": "Listing Agent",
      "propertyAddress": "29 Pepper Tree Court, Warrenton, VA 20186",
      "disbursementDate": "2025-10-22",
      "transactionType": "Purchase",
      "settlementFee": 523.86,
      "lendersPolicy": 200.0,
      "ownersPolicy": 1791.5,
      "fileFee": 1555.88,
      "revenue": 959.48
    },
    {
      "id": "d0129",
      "orderNumber": "VA-25-1089",
      "listingAgent": "Yaztka Allen",
      "sellingAgent": "",
      "client": "Yaztka Allen",
      "clientAttribution": "Listing Agent",
      "propertyAddress": "14783 Darbydale Avenue, Woodbridge, VA 22193",
      "disbursementDate": "2025-10-24",
      "transactionType": "Purchase",
      "settlementFee": 795.0,
      "lendersPolicy": 0,
      "ownersPolicy": 0,
      "fileFee": 1555.88,
      "revenue": -760.88
    },
    {
      "id": "d0130",
      "orderNumber": "VA-25-1111",
      "listingAgent": "",
      "sellingAgent": "",
      "client": "",
      "clientAttribution": "Selling Agent",
      "propertyAddress": "13546 Canada Goose Court, Clifton, VA 20124",
      "disbursementDate": "2025-10-31",
      "transactionType": "Refinance",
      "settlementFee": 695.0,
      "lendersPolicy": 601.72,
      "ownersPolicy": 0,
      "fileFee": 777.94,
      "revenue": 518.78
    },
    {
      "id": "d0131",
      "orderNumber": "MD-25-1097",
      "listingAgent": "",
      "sellingAgent": "",
      "client": "",
      "clientAttribution": "Selling Agent",
      "propertyAddress": "14817 Earl Mitchell Avenue, Brandywine, MD 20613",
      "disbursementDate": "2025-10-31",
      "transactionType": "Refinance",
      "settlementFee": 695.0,
      "lendersPolicy": 1683.0,
      "ownersPolicy": 0,
      "fileFee": 777.94,
      "revenue": 1600.06
    },
    {
      "id": "d0132",
      "orderNumber": "VA-25-1090",
      "listingAgent": "LeAnne Anies",
      "sellingAgent": "Christine Jones",
      "client": "LeAnne Anies",
      "clientAttribution": "Listing Agent",
      "propertyAddress": "1377 Rock Chapel Road, Herndon, VA 20170",
      "disbursementDate": "2025-10-29",
      "transactionType": "Purchase",
      "settlementFee": 1630.0,
      "lendersPolicy": 200.0,
      "ownersPolicy": 4429.5,
      "fileFee": 1555.88,
      "revenue": 4703.62
    },
    {
      "id": "d0133",
      "orderNumber": "VA-25-1115",
      "listingAgent": "Margaret O'Meara",
      "sellingAgent": "Christine Jones",
      "client": "Margaret O'Meara",
      "clientAttribution": "Listing Agent",
      "propertyAddress": "2468 Windbreak Drive, Alexandria, VA 22306",
      "disbursementDate": "2025-10-29",
      "transactionType": "Purchase",
      "settlementFee": 1630.0,
      "lendersPolicy": 200.0,
      "ownersPolicy": 1909.72,
      "fileFee": 1555.88,
      "revenue": 2183.84
    },
    {
      "id": "d0134",
      "orderNumber": "MD-25-1087",
      "listingAgent": "Missy Aldave",
      "sellingAgent": "Muhammad Sohail",
      "client": "Missy Aldave",
      "clientAttribution": "Listing Agent",
      "propertyAddress": "2120 Cedar Circle Drive, Catonsville, MD 21228",
      "disbursementDate": "2025-10-30",
      "transactionType": "Purchase",
      "settlementFee": 1425.0,
      "lendersPolicy": 275.0,
      "ownersPolicy": 3292.68,
      "fileFee": 1555.88,
      "revenue": 3436.8
    },
    {
      "id": "d0135",
      "orderNumber": "MD-25-1114",
      "listingAgent": "Claire Torres",
      "sellingAgent": "Festus Adeduro",
      "client": "Festus Adeduro",
      "clientAttribution": "Listing Agent",
      "propertyAddress": "16 Rhonda Court, Milford Mill, MD 21244",
      "disbursementDate": "2025-11-07",
      "transactionType": "Purchase",
      "settlementFee": 0,
      "lendersPolicy": 0,
      "ownersPolicy": 0,
      "fileFee": 1555.88,
      "revenue": -1555.88
    },
    {
      "id": "d0136",
      "orderNumber": "VA-25-1116",
      "listingAgent": "Denise Jones",
      "sellingAgent": "TBD TBD",
      "client": "Denise Jones",
      "clientAttribution": "Listing Agent",
      "propertyAddress": "8136 Fedora Drive, Chesterfield, VA 23838",
      "disbursementDate": "2025-11-07",
      "transactionType": "Purchase",
      "settlementFee": 0,
      "lendersPolicy": 0,
      "ownersPolicy": 0,
      "fileFee": 1555.88,
      "revenue": -1555.88
    },
    {
      "id": "d0137",
      "orderNumber": "VA-25-1110",
      "listingAgent": "Sam Nassar",
      "sellingAgent": "Kush Acharya",
      "client": "Sam Nassar",
      "clientAttribution": "Listing Agent",
      "propertyAddress": "8275 Vermont Place, Manassas, VA 20111",
      "disbursementDate": "2025-11-07",
      "transactionType": "Purchase",
      "settlementFee": 0,
      "lendersPolicy": 0,
      "ownersPolicy": 0,
      "fileFee": 1555.88,
      "revenue": -1555.88
    },
    {
      "id": "d0138",
      "orderNumber": "VA-25-1117",
      "listingAgent": "Sara Kasamani",
      "sellingAgent": "Penjulee Areevong",
      "client": "Sara Kasamani",
      "clientAttribution": "Listing Agent",
      "propertyAddress": "103 Crest Court, Stafford, VA 22554",
      "disbursementDate": "2025-11-14",
      "transactionType": "Purchase",
      "settlementFee": 1630.0,
      "lendersPolicy": 200.0,
      "ownersPolicy": 2492.52,
      "fileFee": 1555.88,
      "revenue": 2766.64
    },
    {
      "id": "d0139",
      "orderNumber": "VA-25-1130",
      "listingAgent": "Claire Torres",
      "sellingAgent": "",
      "client": "Penjulee Areevong",
      "clientAttribution": "Listing Agent",
      "propertyAddress": "43582 Old Kinderhook Drive, Ashburn, VA 20147",
      "disbursementDate": "2025-11-14",
      "transactionType": "Purchase",
      "settlementFee": 795.0,
      "lendersPolicy": 0,
      "ownersPolicy": 0,
      "fileFee": 1555.88,
      "revenue": -760.88
    },
    {
      "id": "d0140",
      "orderNumber": "VA-25-1134",
      "listingAgent": "Kelly Martinez",
      "sellingAgent": "Masih Javan",
      "client": "Kelly Martinez",
      "clientAttribution": "Listing Agent",
      "propertyAddress": "1172 Foxhound Court, McLean, VA 22102",
      "disbursementDate": "2025-11-17",
      "transactionType": "Purchase",
      "settlementFee": 1035.0,
      "lendersPolicy": 200.0,
      "ownersPolicy": 5491.4,
      "fileFee": 1555.88,
      "revenue": 5170.52
    },
    {
      "id": "d0141",
      "orderNumber": "MD-25-1126",
      "listingAgent": "",
      "sellingAgent": "",
      "client": "",
      "clientAttribution": "Selling Agent",
      "propertyAddress": "820 North Glover Street, Baltimore, MD 21205",
      "disbursementDate": "2025-11-21",
      "transactionType": "Refinance",
      "settlementFee": 695.0,
      "lendersPolicy": 354.75,
      "ownersPolicy": 0,
      "fileFee": 777.94,
      "revenue": 271.81
    },
    {
      "id": "d0142",
      "orderNumber": "MD-25-1142",
      "listingAgent": "",
      "sellingAgent": "Hafiz Habib ur Rehman",
      "client": "Hafiz Habib ur Rehman",
      "clientAttribution": "Selling Agent",
      "propertyAddress": "1807 Parham Way, Baltimore, MD 21228",
      "disbursementDate": "2025-11-21",
      "transactionType": "Purchase",
      "settlementFee": 0,
      "lendersPolicy": 275.0,
      "ownersPolicy": 2574.48,
      "fileFee": 1555.88,
      "revenue": 1293.6
    },
    {
      "id": "d0143",
      "orderNumber": "Pre-25-282",
      "listingAgent": "Rich Thomas",
      "sellingAgent": "",
      "client": "Rich Thomas",
      "clientAttribution": "Listing Agent",
      "propertyAddress": "1906 Thistlewood Drive, Fort Washington, MD 20744",
      "disbursementDate": "2025-11-21",
      "transactionType": "Purchase",
      "settlementFee": 0,
      "lendersPolicy": 200.0,
      "ownersPolicy": 3315.0,
      "fileFee": 1555.88,
      "revenue": 1959.12
    },
    {
      "id": "d0144",
      "orderNumber": "MD-25-1128",
      "listingAgent": "",
      "sellingAgent": "",
      "client": "",
      "clientAttribution": "Selling Agent",
      "propertyAddress": "10912 Timothy Court, Waldorf, MD 20695",
      "disbursementDate": "2025-12-01",
      "transactionType": "Refinance",
      "settlementFee": 0,
      "lendersPolicy": 857.5,
      "ownersPolicy": 0,
      "fileFee": 777.94,
      "revenue": 79.56
    },
    {
      "id": "d0145",
      "orderNumber": "DC-25-1152",
      "listingAgent": "Janel Moore",
      "sellingAgent": "Kelly Martinez",
      "client": "Janel Moore",
      "clientAttribution": "Listing Agent",
      "propertyAddress": "2205 Rand Place Northeast, Washington, DC 20002",
      "disbursementDate": "2025-11-24",
      "transactionType": "Purchase",
      "settlementFee": 0,
      "lendersPolicy": 1094.1,
      "ownersPolicy": 1940.1,
      "fileFee": 1555.88,
      "revenue": 1478.32
    },
    {
      "id": "d0146",
      "orderNumber": "VA-25-1150",
      "listingAgent": "Sunny Yeon",
      "sellingAgent": "Yony Kifle",
      "client": "Sunny Yeon",
      "clientAttribution": "Listing Agent",
      "propertyAddress": "6225 Summit Point Court, Alexandria, VA 22310",
      "disbursementDate": "2025-11-24",
      "transactionType": "Purchase",
      "settlementFee": 1035.0,
      "lendersPolicy": 200.0,
      "ownersPolicy": 3642.0,
      "fileFee": 1555.88,
      "revenue": 3321.12
    },
    {
      "id": "d0147",
      "orderNumber": "MD-25-1131",
      "listingAgent": "Dusty Ellinger",
      "sellingAgent": "Michael Diressie",
      "client": "Dusty Ellinger",
      "clientAttribution": "Listing Agent",
      "propertyAddress": "8700 Kiama Road, Laurel, MD 20708",
      "disbursementDate": "2025-11-25",
      "transactionType": "Purchase",
      "settlementFee": 0,
      "lendersPolicy": 275.0,
      "ownersPolicy": 3165.02,
      "fileFee": 1555.88,
      "revenue": 1884.14
    },
    {
      "id": "d0148",
      "orderNumber": "MD-25-1169",
      "listingAgent": "Seth Loar",
      "sellingAgent": "Beverly Goodwin",
      "client": "Seth Loar",
      "clientAttribution": "Listing Agent",
      "propertyAddress": "13204 Barrelville Road Northwest, Mount Savage, MD 21545",
      "disbursementDate": "2025-12-01",
      "transactionType": "Purchase",
      "settlementFee": 1290.0,
      "lendersPolicy": 0,
      "ownersPolicy": 360.0,
      "fileFee": 1555.88,
      "revenue": 94.12
    },
    {
      "id": "d0149",
      "orderNumber": "MD-25-1104",
      "listingAgent": "",
      "sellingAgent": "Muhammad Sohail",
      "client": "Muhammad Sohail",
      "clientAttribution": "Selling Agent",
      "propertyAddress": "7636 Tall Pin Oak Drive, 111, Elkridge, MD 21075",
      "disbursementDate": "2025-12-03",
      "transactionType": "Purchase",
      "settlementFee": 1625.0,
      "lendersPolicy": 275.0,
      "ownersPolicy": 2648.64,
      "fileFee": 1555.88,
      "revenue": 2992.76
    },
    {
      "id": "d0150",
      "orderNumber": "VA-25-1151",
      "listingAgent": "Maggie Hatfield",
      "sellingAgent": "Farzad Maghsoudi",
      "client": "Maggie Hatfield",
      "clientAttribution": "Listing Agent",
      "propertyAddress": "42533 Magellan Square, Brambleton, VA 20148",
      "disbursementDate": "2025-12-03",
      "transactionType": "Purchase",
      "settlementFee": 1515.0,
      "lendersPolicy": 1819.32,
      "ownersPolicy": 0,
      "fileFee": 1555.88,
      "revenue": 1778.44
    },
    {
      "id": "d0151",
      "orderNumber": "VA-25-1154",
      "listingAgent": "Verria Hairston",
      "sellingAgent": "Jose Coraspe",
      "client": "Verria Hairston",
      "clientAttribution": "Listing Agent",
      "propertyAddress": "10625 Provincial Drive, E, Manassas, VA 20109",
      "disbursementDate": "2025-12-10",
      "transactionType": "Purchase",
      "settlementFee": 1120.0,
      "lendersPolicy": 200.0,
      "ownersPolicy": 1241.28,
      "fileFee": 1555.88,
      "revenue": 1005.4
    },
    {
      "id": "d0152",
      "orderNumber": "VA-25-1154-A",
      "listingAgent": "",
      "sellingAgent": "",
      "client": "",
      "clientAttribution": "Selling Agent",
      "propertyAddress": "10625 Provincial Drive, E, Manassas, VA 20109",
      "disbursementDate": "2025-12-10",
      "transactionType": "Subordinate Order",
      "settlementFee": 0,
      "lendersPolicy": 0,
      "ownersPolicy": 0,
      "fileFee": 0,
      "revenue": 0
    },
    {
      "id": "d0153",
      "orderNumber": "MD-25-1132",
      "listingAgent": "",
      "sellingAgent": "",
      "client": "",
      "clientAttribution": "Selling Agent",
      "propertyAddress": "11706 Lone Tree Court, Columbia, MD 21044",
      "disbursementDate": "2025-12-22",
      "transactionType": "Refinance",
      "settlementFee": 695.0,
      "lendersPolicy": 571.5,
      "ownersPolicy": 0,
      "fileFee": 777.94,
      "revenue": 488.56
    },
    {
      "id": "d0154",
      "orderNumber": "VA-25-1071",
      "listingAgent": "",
      "sellingAgent": "",
      "client": "",
      "clientAttribution": "Selling Agent",
      "propertyAddress": "16755 Birdham Drive, Hamilton, VA 20158",
      "disbursementDate": "2025-12-26",
      "transactionType": "Refinance",
      "settlementFee": 0,
      "lendersPolicy": 2264.67,
      "ownersPolicy": 0,
      "fileFee": 777.94,
      "revenue": 1486.73
    },
    {
      "id": "d0155",
      "orderNumber": "VA-25-977",
      "listingAgent": "",
      "sellingAgent": "",
      "client": "",
      "clientAttribution": "Selling Agent",
      "propertyAddress": "7004 Poppy Drive, McLean, VA 22101",
      "disbursementDate": "2025-12-26",
      "transactionType": "Refinance",
      "settlementFee": 0,
      "lendersPolicy": 3702.97,
      "ownersPolicy": 0,
      "fileFee": 777.94,
      "revenue": 2925.03
    },
    {
      "id": "d0156",
      "orderNumber": "MD-25-1190",
      "listingAgent": "Lee Tessier",
      "sellingAgent": "Muhammad Sohail",
      "client": "Lee Tessier",
      "clientAttribution": "Listing Agent",
      "propertyAddress": "11120 Liberty Road, Owings Mills, MD 21117",
      "disbursementDate": "2025-12-23",
      "transactionType": "Purchase",
      "settlementFee": 945.0,
      "lendersPolicy": 275.0,
      "ownersPolicy": 3661.46,
      "fileFee": 1555.88,
      "revenue": 3325.58
    },
    {
      "id": "d0157",
      "orderNumber": "MD-25-1049",
      "listingAgent": "Umair",
      "sellingAgent": "Umair",
      "client": "Umair",
      "clientAttribution": "Selling Agent",
      "propertyAddress": "4700 Wainwright Circle, Owings Mills, MD 21117",
      "disbursementDate": "2025-10-02",
      "transactionType": "Refinance",
      "settlementFee": 4000.0,
      "lendersPolicy": 653.5,
      "ownersPolicy": 0,
      "fileFee": 777.94,
      "revenue": 3875.56
    },
    {
      "id": "d0158",
      "orderNumber": "VA-25-1054",
      "listingAgent": "",
      "sellingAgent": "",
      "client": "",
      "clientAttribution": "Selling Agent",
      "propertyAddress": "9711 Handerson Place, Unit 206, Manassas Park, VA 20111",
      "disbursementDate": "2026-01-06",
      "transactionType": "Refinance",
      "settlementFee": 0,
      "lendersPolicy": 482.0,
      "ownersPolicy": 0,
      "fileFee": 777.94,
      "revenue": -295.94
    },
    {
      "id": "d0159",
      "orderNumber": "FL-25-1006",
      "listingAgent": "",
      "sellingAgent": "",
      "client": "",
      "clientAttribution": "Selling Agent",
      "propertyAddress": "509 Coconut Isle Drive, Fort Lauderdale, FL 33301",
      "disbursementDate": "2026-01-06",
      "transactionType": "Refinance",
      "settlementFee": 0,
      "lendersPolicy": 11450.0,
      "ownersPolicy": 0,
      "fileFee": 777.94,
      "revenue": 10672.06
    },
    {
      "id": "d0160",
      "orderNumber": "MD-25-1156",
      "listingAgent": "",
      "sellingAgent": "",
      "client": "",
      "clientAttribution": "Selling Agent",
      "propertyAddress": "7612 Finns Lane, Lanham, MD 20706",
      "disbursementDate": "2026-01-06",
      "transactionType": "Refinance",
      "settlementFee": 0,
      "lendersPolicy": 687.5,
      "ownersPolicy": 0,
      "fileFee": 777.94,
      "revenue": -90.44
    }
  ],
  "expenses": [
    {
      "id": "e0001",
      "date": "",
      "client": "Alan De Gracia",
      "expenseType": "Marketing",
      "description": "8.0",
      "amount": 9000.0,
      "notes": ""
    },
    {
      "id": "e0002",
      "date": "",
      "client": "Alan De Gracia",
      "expenseType": "Meal",
      "description": "",
      "amount": 500.0,
      "notes": ""
    },
    {
      "id": "e0003",
      "date": "",
      "client": "Yony Kifle",
      "expenseType": "Gift",
      "description": "",
      "amount": 600.0,
      "notes": ""
    },
    {
      "id": "e0004",
      "date": "",
      "client": "Umair",
      "expenseType": "Event",
      "description": "",
      "amount": 5000.0,
      "notes": ""
    }
  ]
};
